#!/usr/bin/env python
#
# Cancel Navigation Goal
#  

#! /usr/bin/env python

import roslib; roslib.load_manifest('pioneer3at')
import rospy
import actionlib

from move_base_msgs.msg import *

if __name__ == '__main__':
    rospy.init_node('movebase_client')
    client = actionlib.SimpleActionClient('/move_base', MoveBaseAction)
    client.wait_for_server()
  
    # Move 1m forward
    goal = MoveBaseAction();    
    goal.target_pose.header.frame_id = "/Pioneer3AT/chassis"
    goal.target_pose.header.stamp = ros.Time.now();
    goal.target_pose.pose.position.x = 1.0;
    goal.target_pose.pose.orientation.w = 1.0;
    
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(10.0))
    
    if(client.getState() == actionlib.SimpleClientGoalState.SUCCEEDED):
        rospy.loginfo("Hooray, the robot moved 1 meter forward");
    else:
        rospy.loginfo("The robot failed to move for some reason");
  
  
  
  
  
  
