#!/usr/bin/env python
#
# Pioneer 3 AT Joystick Control Node
#  
#   Copyright Dereck Wonnacott [2013]
#

import rospy

from geometry_msgs.msg import Twist
from sensor_msgs.msg   import Joy


# Maps joystick to velocity commands
def joyCB(msg):
  motion_enable = (msg.buttons[10] > 0)
  
  cmd_vel_msg = Twist()
  if motion_enable:
    rospy.logdebug("Joy Command Recieved: [Vx:%f, Wz:%f]"%(msg.axes[1], msg.axes[2]))
    cmd_vel_msg.linear.x = msg.axes[1]
    cmd_vel_msg.angular.z = msg.axes[2]
  else
    cmd_vel_msg.linear.x = 0
    cmd_vel_msg.angular.z = 0
    
  cmd_vel_pub.publish(cmd_vel_msg)


# Rebroadcast commands from the autonomous navigation planner
def nav_cmdCB(msg):  
  if ~motion_enable:
    rospy.logdebug("Navigation Command Recieved: [Vx:%f, Wz:%f]"%(msg.linear.x, msg.angular.z))
    cmd_vel_pub.publish(msg)


if __name__ == '__main__':
  rospy.init_node('cmd_vel_listener')
  
  global cmd_vel_pub
  global motion_enable
  
  cmd_vel_pub = rospy.Publisher("/cmd_vel", Twist)
  motion_enable = 0
  
  rospy.Subscriber("/move_base/cmd_vel", Twist, nav_cmdCB)
  rospy.Subscriber("/joy", Joy, joyCB)
  rospy.spin()
  
  
  
  
  
  
  
  
  
