#!/usr/bin/env python
#
# Pioneer 3 AT Joystick Control Node
#  
#   Copyright Dereck Wonnacott [2013]
#

import rospy

from geometry_msgs.msg import Twist
from sensor_msgs.msg   import Joy


# Simply rebroadcast commands from the autonomous navigation planner
def nav_cmdCB(msg):  
  if self.motion_enable:
    rospy.logdebug("Navigation Command Recieved: [Vx:%f, Wz:%f]"%(msg.linear.x, msg.angular.z))
    self.cmd_vel_pub.publish(msg)


# Maps joystick to velocity commands
def joy_CB(msg):
  self.motion_enable = (msg.buttons[10] > 0)

  if self.motion_enable:
    rospy.logdebug("Joy Command Recieved: [Vx:%f, Wz:%f]"%(msg.axis[1], msg.axis[3]))
    cmd_vel_msg = Twist()
    cmd_vel_msg.linear.x = msg.axis[1]
    cmd_vel_msg.angular.z = msg.axis[3]
    self.cmd_vel_pub.publish(cmd_vel_msg)


if __name__ == '__main__':
  rospy.init_node('cmd_vel_listener')
  self.cmd_vel_pub = rospy.Publisher("/cmd_vel", node_example_data)
  rospy.Subscriber("/move_base/cmd_vel", Twist, nav_cmdCB)
  rospy.Subscriber("/joy", Joy, joyCB)
  rospy.spin()
  
  
  
  
  
  
  
  
  
