#!/usr/bin/env python
#
# Simple tf broadcaster from /pose topic from a bag file.
# Dereck Wonnacott (2013)
#  

import rospy
import tf
from nav_msgs.msg  import Odometry


def subCB(msg):
  P = (msg.pose.pose.position.x, msg.pose.pose.position.y, msg.pose.pose.position.z )
  Q = (msg.pose.pose.orientation.x, msg.pose.pose.orientation.y, msg.pose.pose.orientation.z, msg.pose.pose.orientation.w)
  
  br = tf.TransformBroadcaster()
  br.sendTransform(P, Q, rospy.Time.now(), "/Pioneer3AT/base_link", "world")

if __name__ == '__main__':
  rospy.init_node('tf_from_pose')
  
  rospy.Subscriber("/Pioneer3AT/pose", Odometry, subCB)
  rospy.spin()
  
  
  
  
  
  
  
  
  
